(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"EWET",
  Authors -> {"Javier Marti'nez", "Juan Jose' Sanz Cillero"},
  Date -> "24/05/2022",
  Institutions -> {"Universidad Complutense de Madrid"},
  Emails -> {"javmar21@ucm.es", "jusanz02@ucm.es"},
  Version -> "1"};

FR$ClassesTranslation={};

FR$InteractionOrderPerturbativeExpansion={{QED, 0}};

FR$GoldstoneList={};

(*     Declared indices    *)

IndexRange[ Index[SU2W] ] = Range[ 3 ]

(*     Declared particles    *)

M$ClassesDescription = {
V[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> "\[Gamma]",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {} },

V[2] == {
    SelfConjugate -> True,
    PropagatorLabel -> "Z",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {} },

V[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorLabel -> "W",
    PropagatorType -> Sine,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {} },

S[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> "H",
    PropagatorType -> Straight,
    PropagatorArrow -> None,
    Mass -> MH,
    Indices -> {} },

S[2] == {
    SelfConjugate -> True,
    PropagatorLabel -> ComposedChar["\\pi", Null, 0],
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {} },

S[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorLabel -> "\[Pi]",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {} }
}


(*        Definitions       *)


MZ[ ___ ] := MZ;
MW[ ___ ] := MW;
MH[ ___ ] := MH;




(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ S[1] , S[1] , S[1] , S[1] ] == {{((-12*I)*(-2*F10n4 + b4*MH^2*vev^2))/vev^4, 0}, {((8*I)*F8n0)/vev^4, 0}, {((8*I)*F8n0)/vev^4, 0}, {((8*I)*F8n0)/vev^4, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[1] , S[1] , S[1] ] == {{((-3*I)*(-2*F10n3 + b3*MH^2*vev^2))/vev^3, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[3] , -S[3] , V[1] , V[1] ] == {{((-4*I)*EL^2*F3n0)/vev^2, 0}, {((-4*I)*EL^2*F3n0)/vev^2, 0}, {((-4*I)*EL^2*F3n0)/vev^2, 0}, {((-4*I)*EL^2*F3n0)/vev^2, 0}, {((-8*I)*EL^2*F1n0)/vev^2, 0}, {(2*I)*EL^2, 0}, {((4*I)*EL^2*F3n0)/vev^2, 0}, {((4*I)*EL^2*F3n0)/vev^2, 0}, {((4*I)*EL^2*F3n0)/vev^2, 0}, {((4*I)*EL^2*F3n0)/vev^2, 0}, {((8*I)*EL^2*F1n0)/vev^2, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[2] , S[3] , -S[3] , V[1] ] == {{(-4*EL^3*F10n0)/(cw^2*vev^3), 0}, {(4*EL*FF1n0)/vev^3, 0}, {(4*EL*FF1n0)/vev^3, 0}, {(-4*EL*FF1n0)/vev^3, 0}, {(-4*EL*FF1n0)/vev^3, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[1] , S[1] , S[2] , S[2] ] == {{0, 0}, {((4*I)*F7n0)/vev^4, 0}, {((4*I)*F7n0)/vev^4, 0}, {((8*I)*F6n0)/vev^4, 0}, {((-2*I)*(2*EL^2*F10n2 + b*cw^2*vev^2))/(cw^2*vev^4), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[2] , S[2] , S[3] , -S[3] ] == {{0, 0}, {((16*I)*F4n0)/vev^4, 0}, {((16*I)*F4n0)/vev^4, 0}, {((32*I)*F5n0)/vev^4, 0}, {((2*I)/3)/vev^2, 0}, {(((2*I)/3)*(8*EL^2*F10n0 + cw^2*vev^2))/(cw^2*vev^4), 0}, {((-1/3*I)*(4*EL^2*F10n0 + cw^2*vev^2))/(cw^2*vev^4), 0}, {((-1/3*I)*(4*EL^2*F10n0 + cw^2*vev^2))/(cw^2*vev^4), 0}, {((-1/3*I)*(4*EL^2*F10n0 + cw^2*vev^2))/(cw^2*vev^4), 0}, {((-1/3*I)*(4*EL^2*F10n0 + cw^2*vev^2))/(cw^2*vev^4), 0}},

C[ S[1] , S[2] , S[2] ] == {{0, 0}, {((-2*I)*(EL^2*F10n1 + a*cw^2*vev^2))/(cw^2*vev^3), 0}, {0, 0}, {0, 0}},

C[ S[2] , S[2] , S[2] , S[2] ] == {{0, 0}, {((32*I)*(F4n0 + F5n0))/vev^4, 0}, {((32*I)*(F4n0 + F5n0))/vev^4, 0}, {((32*I)*(F4n0 + F5n0))/vev^4, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[3] , -S[3] , V[1] ] == {{(-I)*EL, 0}, {I*EL, 0}, {((4*I)*EL*F3n0)/vev^2, 0}, {((-4*I)*EL*F3n0)/vev^2, 0}},

C[ S[1] , S[3] , -S[3] , V[1] ] == {{0, 0}, {((-2*I)*EL*F9n0)/vev^3, 0}, {((2*I)*EL*F9n0)/vev^3, 0}, {((2*I)*EL*F9n0)/vev^3, 0}, {((-2*I)*EL*F9n0)/vev^3, 0}, {((-2*I)*a*EL)/vev, 0}, {((2*I)*a*EL)/vev, 0}, {((4*I)*EL*F3n1)/vev^3, 0}, {((-4*I)*EL*F3n1)/vev^3, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[1] , S[2] , S[3] , -S[3] ] == {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {(2*EL^2*F10n1)/(cw^2*vev^4), 0}, {(-2*EL^2*F10n1)/(cw^2*vev^4), 0}},

C[ S[2] , S[3] , -S[3] ] == {{0, 0}, {0, 0}, {(2*EL^2*F10n0)/(cw^2*vev^3), 0}, {(-2*EL^2*F10n0)/(cw^2*vev^3), 0}},

C[ S[3] , S[3] , -S[3] , -S[3] ] == {{0, 0}, {((16*I)*(F4n0 + 2*F5n0))/vev^4, 0}, {((16*I)*(F4n0 + 2*F5n0))/vev^4, 0}, {((32*I)*F4n0)/vev^4, 0}, {(((2*I)/3)*((6*EL^2*F10n0)/cw^2 - vev^2))/vev^4, 0}, {(((2*I)/3)*((6*EL^2*F10n0)/cw^2 - vev^2))/vev^4, 0}, {((-2*I)*EL^2*F10n0)/(cw^2*vev^4) + (I/3)/vev^2, 0}, {((-2*I)*EL^2*F10n0)/(cw^2*vev^4) + (I/3)/vev^2, 0}, {((-2*I)*EL^2*F10n0)/(cw^2*vev^4) + (I/3)/vev^2, 0}, {((-2*I)*EL^2*F10n0)/(cw^2*vev^4) + (I/3)/vev^2, 0}},

C[ S[1] , S[1] , S[3] , -S[3] ] == {{0, 0}, {((4*I)*F7n0)/vev^4, 0}, {((4*I)*F7n0)/vev^4, 0}, {((8*I)*F6n0)/vev^4, 0}, {((-2*I)*b)/vev^2, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[1] , S[3] , -S[3] ] == {{0, 0}, {((-2*I)*a)/vev, 0}, {0, 0}, {0, 0}},

C[ S[1] , S[1] , S[2] , V[1] ] == {{0, 0}, {0, 0}, {(2*EL*FF3n1)/vev^3, 0}, {0, 0}, {(-2*EL*FF3n1)/vev^3, 0}, {0, 0}, {0, 0}, {(2*EL*FF3n1)/vev^3, 0}, {(-2*EL*FF3n1)/vev^3, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[1] , S[2] , V[1] ] == {{0, 0}, {0, 0}, {(2*EL*FF3n0)/vev^2, 0}, {(-2*EL*FF3n0)/vev^2, 0}},

C[ S[1] , S[1] , V[1] , V[1] ] == {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {((4*I)*EL^2*(2*F11n2 + F1n2 + 2*F2n2))/vev^2, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {((-4*I)*EL^2*(2*F11n2 + F1n2 + 2*F2n2))/vev^2, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[1] , V[1] , V[1] ] == {{((2*I)*EL^2*(2*F11n1 + F1n1 + 2*F2n1))/vev, 0}, {((-2*I)*EL^2*(2*F11n1 + F1n1 + 2*F2n1))/vev, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[1] , -S[3] , V[1] , V[3] ] == {{-((EL^2*(F9n0 - FF3n0))/(sw*vev^2)), 0}, {(-2*EL^2*F3n1)/(sw*vev^2), 0}, {-((EL^2*(F9n0 + FF3n0))/(sw*vev^2)), 0}, {0, 0}, {(-2*EL^2*F1n1)/(sw*vev^2), 0}, {(a*EL^2)/sw, 0}, {(EL^2*(F9n0 - FF3n0))/(sw*vev^2), 0}, {(EL^2*(F9n0 + FF3n0))/(sw*vev^2), 0}, {(2*EL^2*F3n1)/(sw*vev^2), 0}, {0, 0}, {(2*EL^2*F1n1)/(sw*vev^2), 0}, {(EL^2*(F9n0 + FF3n0))/(sw*vev^2), 0}, {-((EL^2*(F9n0 + FF3n0))/(sw*vev^2)), 0}, {0, 0}},

C[ S[2] , -S[3] , V[1] , V[3] ] == {{((-2*I)*EL^2*FF1n0)/(sw*vev^2), 0}, {((2*I)*EL^2*F3n0)/(sw*vev^2), 0}, {((2*I)*EL^2*(F3n0 + FF1n0))/(sw*vev^2), 0}, {0, 0}, {((2*I)*EL^2*F1n0)/(sw*vev^2), 0}, {((-1/2*I)*EL^2)/sw, 0}, {((2*I)*EL^2*FF1n0)/(sw*vev^2), 0}, {((-2*I)*EL^2*(F3n0 + FF1n0))/(sw*vev^2), 0}, {((-2*I)*EL^2*F3n0)/(sw*vev^2), 0}, {0, 0}, {((-2*I)*EL^2*F1n0)/(sw*vev^2), 0}, {((-2*I)*EL^2*(F3n0 + FF1n0))/(sw*vev^2), 0}, {((2*I)*EL^2*(F3n0 + FF1n0))/(sw*vev^2), 0}, {0, 0}},

C[ S[1] , S[2] , -S[3] , V[3] ] == {{0, 0}, {(I*EL*(F9n0 + FF3n0))/(sw*vev^3), 0}, {((-I)*EL*(F9n0 + FF3n0))/(sw*vev^3), 0}, {((-I)*EL*(F9n0 + FF3n0))/(sw*vev^3), 0}, {(I*EL*(F9n0 + FF3n0))/(sw*vev^3), 0}, {(I*EL*(2*EL^2*F10n1 + a*cw^2*vev^2))/(cw^2*sw*vev^3), 0}, {((-I)*a*EL)/(sw*vev), 0}, {((-2*I)*EL*(F3n1 + FF1n1))/(sw*vev^3), 0}, {((2*I)*EL*(F3n1 + FF1n1))/(sw*vev^3), 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[2] , S[2] , -S[3] , V[3] ] == {{(6*EL^3*F10n0 + cw^2*EL*vev^2)/(3*cw^2*sw*vev^3), 0}, {0, 0}, {(-2*EL*(F3n0 + FF1n0))/(sw*vev^3), 0}, {0, 0}, {(2*EL*(F3n0 + FF1n0))/(sw*vev^3), 0}, {(6*EL^3*F10n0 + cw^2*EL*vev^2)/(3*cw^2*sw*vev^3), 0}, {(-2*EL)/(3*sw*vev), 0}, {(-2*EL*(F3n0 + FF1n0))/(sw*vev^3), 0}, {(2*EL*(F3n0 + FF1n0))/(sw*vev^3), 0}, {(-16*EL*F5n0)/(sw*vev^3), 0}, {(-8*EL*F4n0)/(sw*vev^3), 0}, {(-8*EL*F4n0)/(sw*vev^3), 0}},

C[ S[2] , -S[3] , V[3] ] == {{((I/2)*EL*(1 + (4*EL^2*F10n0)/(cw^2*vev^2)))/sw, 0}, {((-1/2*I)*EL)/sw, 0}, {((-2*I)*EL*(F3n0 + FF1n0))/(sw*vev^2), 0}, {((2*I)*EL*(F3n0 + FF1n0))/(sw*vev^2), 0}},

C[ S[3] , -S[3] , -S[3] , V[3] ] == {{(2*EL*(-6*EL^2*F10n0 + cw^2*vev^2))/(3*cw^2*sw*vev^3), 0}, {(-2*EL*(F3n0 + FF1n0))/(sw*vev^3), 0}, {(-2*EL*(F3n0 + FF1n0))/(sw*vev^3), 0}, {(2*EL*(F3n0 + FF1n0))/(sw*vev^3), 0}, {(2*EL*(F3n0 + FF1n0))/(sw*vev^3), 0}, {(6*EL^3*F10n0 - cw^2*EL*vev^2)/(3*cw^2*sw*vev^3), 0}, {(6*EL^3*F10n0 - cw^2*EL*vev^2)/(3*cw^2*sw*vev^3), 0}, {0, 0}, {0, 0}, {(-8*EL*(F4n0 + 2*F5n0))/(sw*vev^3), 0}, {(-8*EL*(F4n0 + 2*F5n0))/(sw*vev^3), 0}, {(-16*EL*F4n0)/(sw*vev^3), 0}},

C[ S[1] , S[1] , -S[3] , V[3] ] == {{0, 0}, {0, 0}, {(EL*(F9n1 + FF3n1))/(sw*vev^3), 0}, {0, 0}, {-((EL*(F9n1 + FF3n1))/(sw*vev^3)), 0}, {0, 0}, {(b*EL)/(sw*vev), 0}, {(EL*(F9n1 + FF3n1))/(sw*vev^3), 0}, {-((EL*(F9n1 + FF3n1))/(sw*vev^3)), 0}, {(-4*EL*F6n0)/(sw*vev^3), 0}, {(-2*EL*F7n0)/(sw*vev^3), 0}, {(-2*EL*F7n0)/(sw*vev^3), 0}},

C[ S[1] , -S[3] , V[3] ] == {{0, 0}, {(a*EL)/sw, 0}, {(EL*(F9n0 + FF3n0))/(sw*vev^2), 0}, {-((EL*(F9n0 + FF3n0))/(sw*vev^2)), 0}},

C[ -S[3] , V[1] , V[3] ] == {{(-2*EL^2*F1n0)/(sw*vev), 0}, {(2*EL^2*F1n0)/(sw*vev), 0}, {(-2*EL^2*F3n0)/(sw*vev), 0}, {(EL^2*vev)/(2*sw), 0}, {(2*EL^2*F3n0)/(sw*vev), 0}, {0, 0}, {0, 0}},

C[ S[1] , S[3] , V[1] , -V[3] ] == {{(EL^2*(F9n0 - FF3n0))/(sw*vev^2), 0}, {(2*EL^2*F3n1)/(sw*vev^2), 0}, {(EL^2*(F9n0 + FF3n0))/(sw*vev^2), 0}, {0, 0}, {(2*EL^2*F1n1)/(sw*vev^2), 0}, {-((a*EL^2)/sw), 0}, {-((EL^2*(F9n0 - FF3n0))/(sw*vev^2)), 0}, {-((EL^2*(F9n0 + FF3n0))/(sw*vev^2)), 0}, {(-2*EL^2*F3n1)/(sw*vev^2), 0}, {0, 0}, {(-2*EL^2*F1n1)/(sw*vev^2), 0}, {-((EL^2*(F9n0 + FF3n0))/(sw*vev^2)), 0}, {(EL^2*(F9n0 + FF3n0))/(sw*vev^2), 0}, {0, 0}},

C[ S[2] , S[3] , V[1] , -V[3] ] == {{((-2*I)*EL^2*FF1n0)/(sw*vev^2), 0}, {((2*I)*EL^2*F3n0)/(sw*vev^2), 0}, {((2*I)*EL^2*(F3n0 + FF1n0))/(sw*vev^2), 0}, {0, 0}, {((2*I)*EL^2*F1n0)/(sw*vev^2), 0}, {((-1/2*I)*EL^2)/sw, 0}, {((2*I)*EL^2*FF1n0)/(sw*vev^2), 0}, {((-2*I)*EL^2*(F3n0 + FF1n0))/(sw*vev^2), 0}, {((-2*I)*EL^2*F3n0)/(sw*vev^2), 0}, {0, 0}, {((-2*I)*EL^2*F1n0)/(sw*vev^2), 0}, {((-2*I)*EL^2*(F3n0 + FF1n0))/(sw*vev^2), 0}, {((2*I)*EL^2*(F3n0 + FF1n0))/(sw*vev^2), 0}, {0, 0}},

C[ S[1] , S[2] , S[3] , -V[3] ] == {{0, 0}, {((-I)*EL*(F9n0 + FF3n0))/(sw*vev^3), 0}, {(I*EL*(F9n0 + FF3n0))/(sw*vev^3), 0}, {(I*EL*(F9n0 + FF3n0))/(sw*vev^3), 0}, {((-I)*EL*(F9n0 + FF3n0))/(sw*vev^3), 0}, {((-I)*EL*(2*EL^2*F10n1 + a*cw^2*vev^2))/(cw^2*sw*vev^3), 0}, {(I*a*EL)/(sw*vev), 0}, {((2*I)*EL*(F3n1 + FF1n1))/(sw*vev^3), 0}, {((-2*I)*EL*(F3n1 + FF1n1))/(sw*vev^3), 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[2] , S[2] , S[3] , -V[3] ] == {{(6*EL^3*F10n0 + cw^2*EL*vev^2)/(3*cw^2*sw*vev^3), 0}, {0, 0}, {(-2*EL*(F3n0 + FF1n0))/(sw*vev^3), 0}, {0, 0}, {(2*EL*(F3n0 + FF1n0))/(sw*vev^3), 0}, {(6*EL^3*F10n0 + cw^2*EL*vev^2)/(3*cw^2*sw*vev^3), 0}, {(-2*EL)/(3*sw*vev), 0}, {(-2*EL*(F3n0 + FF1n0))/(sw*vev^3), 0}, {(2*EL*(F3n0 + FF1n0))/(sw*vev^3), 0}, {(-16*EL*F5n0)/(sw*vev^3), 0}, {(-8*EL*F4n0)/(sw*vev^3), 0}, {(-8*EL*F4n0)/(sw*vev^3), 0}},

C[ S[2] , S[3] , -V[3] ] == {{((-1/2*I)*EL*(4*EL^2*F10n0 + cw^2*vev^2))/(cw^2*sw*vev^2), 0}, {((I/2)*EL)/sw, 0}, {((2*I)*EL*(F3n0 + FF1n0))/(sw*vev^2), 0}, {((-2*I)*EL*(F3n0 + FF1n0))/(sw*vev^2), 0}},

C[ S[1] , S[1] , S[3] , -V[3] ] == {{0, 0}, {0, 0}, {(EL*(F9n1 + FF3n1))/(sw*vev^3), 0}, {0, 0}, {-((EL*(F9n1 + FF3n1))/(sw*vev^3)), 0}, {0, 0}, {(b*EL)/(sw*vev), 0}, {(EL*(F9n1 + FF3n1))/(sw*vev^3), 0}, {-((EL*(F9n1 + FF3n1))/(sw*vev^3)), 0}, {(-4*EL*F6n0)/(sw*vev^3), 0}, {(-2*EL*F7n0)/(sw*vev^3), 0}, {(-2*EL*F7n0)/(sw*vev^3), 0}},

C[ S[1] , S[3] , -V[3] ] == {{0, 0}, {(a*EL)/sw, 0}, {(EL*(F9n0 + FF3n0))/(sw*vev^2), 0}, {-((EL*(F9n0 + FF3n0))/(sw*vev^2)), 0}},

C[ S[3] , S[3] , -S[3] , -V[3] ] == {{(6*EL^3*F10n0 - cw^2*EL*vev^2)/(3*cw^2*sw*vev^3), 0}, {0, 0}, {(2*EL*(F3n0 + FF1n0))/(sw*vev^3), 0}, {0, 0}, {(-2*EL*(F3n0 + FF1n0))/(sw*vev^3), 0}, {(6*EL^3*F10n0 - cw^2*EL*vev^2)/(3*cw^2*sw*vev^3), 0}, {(2*EL*(-6*EL^2*F10n0 + cw^2*vev^2))/(3*cw^2*sw*vev^3), 0}, {(2*EL*(F3n0 + FF1n0))/(sw*vev^3), 0}, {(-2*EL*(F3n0 + FF1n0))/(sw*vev^3), 0}, {(-16*EL*F4n0)/(sw*vev^3), 0}, {(-8*EL*(F4n0 + 2*F5n0))/(sw*vev^3), 0}, {(-8*EL*(F4n0 + 2*F5n0))/(sw*vev^3), 0}},

C[ S[3] , V[1] , -V[3] ] == {{(2*EL^2*F1n0)/(sw*vev), 0}, {(-2*EL^2*F1n0)/(sw*vev), 0}, {(2*EL^2*F3n0)/(sw*vev), 0}, {-1/2*(EL^2*vev)/sw, 0}, {(-2*EL^2*F3n0)/(sw*vev), 0}, {0, 0}, {0, 0}},

C[ S[1] , S[1] , V[3] , -V[3] ] == {{((-1/2*I)*EL^2*(F9n1 + FF3n1))/(sw^2*vev^2), 0}, {((-1/2*I)*EL^2*(F9n1 + FF3n1))/(sw^2*vev^2), 0}, {((-1/2*I)*EL^2*(F9n1 + FF3n1))/(sw^2*vev^2), 0}, {((-1/2*I)*EL^2*(F9n1 + FF3n1))/(sw^2*vev^2), 0}, {((4*I)*EL^2*(F2n2 + FF2n2))/(sw^2*vev^2), 0}, {((I/2)*b*EL^2)/sw^2, 0}, {((I/2)*EL^2*(F9n1 + FF3n1))/(sw^2*vev^2), 0}, {((I/2)*EL^2*(F9n1 + FF3n1))/(sw^2*vev^2), 0}, {((I/2)*EL^2*(F9n1 + FF3n1))/(sw^2*vev^2), 0}, {((I/2)*EL^2*(F9n1 + FF3n1))/(sw^2*vev^2), 0}, {((-4*I)*EL^2*(F2n2 + FF2n2))/(sw^2*vev^2), 0}, {((-I)*EL^2*F7n0)/(sw^2*vev^2), 0}, {((-I)*EL^2*F7n0)/(sw^2*vev^2), 0}, {((-2*I)*EL^2*F6n0)/(sw^2*vev^2), 0}},

C[ S[1] , V[3] , -V[3] ] == {{((2*I)*EL^2*(F2n1 + FF2n1))/(sw^2*vev), 0}, {((-2*I)*EL^2*(F2n1 + FF2n1))/(sw^2*vev), 0}, {((-1/2*I)*EL^2*(F9n0 + FF3n0))/(sw^2*vev), 0}, {((I/2)*a*EL^2*vev)/sw^2, 0}, {((I/2)*EL^2*(F9n0 + FF3n0))/(sw^2*vev), 0}, {((-1/2*I)*EL^2*(F9n0 + FF3n0))/(sw^2*vev), 0}, {((I/2)*EL^2*(F9n0 + FF3n0))/(sw^2*vev), 0}},

C[ S[1] , S[1] , S[2] , V[2] ] == {{0, 0}, {0, 0}, {(EL*(cw^2*(F9n1 + FF3n1) + (F9n1 - FF3n1)*sw^2))/(cw*sw*vev^3), 0}, {0, 0}, {-((EL*(cw^2*(F9n1 + FF3n1) + (F9n1 - FF3n1)*sw^2))/(cw*sw*vev^3)), 0}, {0, 0}, {(EL*(cw^2 + sw^2)*(2*EL^2*F10n2 + b*cw^2*vev^2))/(cw^3*sw*vev^3), 0}, {(EL*(cw^2*(F9n1 + FF3n1) + (F9n1 - FF3n1)*sw^2))/(cw*sw*vev^3), 0}, {-((EL*(cw^2*(F9n1 + FF3n1) + (F9n1 - FF3n1)*sw^2))/(cw*sw*vev^3)), 0}, {(-4*EL*F6n0*(cw^2 + sw^2))/(cw*sw*vev^3), 0}, {(-2*EL*F7n0*(cw^2 + sw^2))/(cw*sw*vev^3), 0}, {(-2*EL*F7n0*(cw^2 + sw^2))/(cw*sw*vev^3), 0}},

C[ S[1] , S[2] , V[2] ] == {{0, 0}, {(EL*(cw^2 + sw^2)*(EL^2*F10n1 + a*cw^2*vev^2))/(cw^3*sw*vev^2), 0}, {(EL*(cw^2*(F9n0 + FF3n0) + (F9n0 - FF3n0)*sw^2))/(cw*sw*vev^2), 0}, {-((EL*(cw^2*(F9n0 + FF3n0) + (F9n0 - FF3n0)*sw^2))/(cw*sw*vev^2)), 0}},

C[ S[3] , -S[3] , V[1] , V[2] ] == {{((-2*I)*EL^2*(cw^2*(F3n0 - FF1n0) - (F3n0 + FF1n0)*sw^2))/(cw*sw*vev^2), 0}, {((-2*I)*EL^2*(cw^2*(F3n0 - FF1n0) - (F3n0 + FF1n0)*sw^2))/(cw*sw*vev^2), 0}, {((-2*I)*EL^2*(cw^2*(F3n0 + FF1n0) + (-F3n0 + FF1n0)*sw^2))/(cw*sw*vev^2), 0}, {((-2*I)*EL^2*(cw^2*(F3n0 + FF1n0) + (-F3n0 + FF1n0)*sw^2))/(cw*sw*vev^2), 0}, {((-4*I)*EL^2*F1n0*(cw - sw)*(cw + sw))/(cw*sw*vev^2), 0}, {((-I)*EL^2*(2*EL^2*F10n0*sw^2 - cw^4*vev^2 + cw^2*(2*EL^2*F10n0 + sw^2*vev^2)))/(cw^3*sw*vev^2), 0}, {((2*I)*EL^2*(cw^2*(F3n0 - FF1n0) - (F3n0 + FF1n0)*sw^2))/(cw*sw*vev^2), 0}, {((2*I)*EL^2*(cw^2*(F3n0 + FF1n0) + (-F3n0 + FF1n0)*sw^2))/(cw*sw*vev^2), 0}, {((2*I)*EL^2*(cw^2*(F3n0 - FF1n0) - (F3n0 + FF1n0)*sw^2))/(cw*sw*vev^2), 0}, {((2*I)*EL^2*(cw^2*(F3n0 + FF1n0) + (-F3n0 + FF1n0)*sw^2))/(cw*sw*vev^2), 0}, {((4*I)*EL^2*F1n0*(cw - sw)*(cw + sw))/(cw*sw*vev^2), 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[2] , S[3] , -S[3] , V[2] ] == {{(-2*EL*(2*EL^2*F10n0*sw^2 + cw^4*vev^2 + cw^2*(8*EL^2*F10n0 + sw^2*vev^2)))/(3*cw^3*sw*vev^3), 0}, {(2*EL*(cw^2*(F3n0 + FF1n0) + (F3n0 - FF1n0)*sw^2))/(cw*sw*vev^3), 0}, {(2*EL*(cw^2*(F3n0 + FF1n0) + (F3n0 - FF1n0)*sw^2))/(cw*sw*vev^3), 0}, {(-2*EL*(cw^2*(F3n0 + FF1n0) + (F3n0 - FF1n0)*sw^2))/(cw*sw*vev^3), 0}, {(-2*EL*(cw^2*(F3n0 + FF1n0) + (F3n0 - FF1n0)*sw^2))/(cw*sw*vev^3), 0}, {(EL*(cw^2 + sw^2)*(2*EL^2*F10n0 + cw^2*vev^2))/(3*cw^3*sw*vev^3), 0}, {(EL*(cw^2 + sw^2)*(2*EL^2*F10n0 + cw^2*vev^2))/(3*cw^3*sw*vev^3), 0}, {0, 0}, {0, 0}, {(-8*EL*F4n0*(cw^2 + sw^2))/(cw*sw*vev^3), 0}, {(-8*EL*F4n0*(cw^2 + sw^2))/(cw*sw*vev^3), 0}, {(-16*EL*F5n0*(cw^2 + sw^2))/(cw*sw*vev^3), 0}},

C[ S[1] , S[3] , -S[3] , V[2] ] == {{0, 0}, {((-I)*EL*(cw^2*(F9n0 + FF3n0) + (-F9n0 + FF3n0)*sw^2))/(cw*sw*vev^3), 0}, {(I*EL*(cw^2*(F9n0 + FF3n0) + (-F9n0 + FF3n0)*sw^2))/(cw*sw*vev^3), 0}, {(I*EL*(cw^2*(F9n0 + FF3n0) + (-F9n0 + FF3n0)*sw^2))/(cw*sw*vev^3), 0}, {((-I)*EL*(cw^2*(F9n0 + FF3n0) + (-F9n0 + FF3n0)*sw^2))/(cw*sw*vev^3), 0}, {(I*EL*(EL^2*F10n1*sw^2 - a*cw^4*vev^2 + cw^2*(EL^2*F10n1 + a*sw^2*vev^2)))/(cw^3*sw*vev^3), 0}, {((-I)*EL*(EL^2*F10n1*sw^2 - a*cw^4*vev^2 + cw^2*(EL^2*F10n1 + a*sw^2*vev^2)))/(cw^3*sw*vev^3), 0}, {((2*I)*EL*(cw^2*(F3n1 + FF1n1) + (-F3n1 + FF1n1)*sw^2))/(cw*sw*vev^3), 0}, {((-2*I)*EL*(cw^2*(F3n1 + FF1n1) + (-F3n1 + FF1n1)*sw^2))/(cw*sw*vev^3), 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[3] , -S[3] , V[2] ] == {{((I/2)*EL*(2*EL^2*F10n0*sw^2 - cw^4*vev^2 + cw^2*(2*EL^2*F10n0 + sw^2*vev^2)))/(cw^3*sw*vev^2), 0}, {((-1/2*I)*EL*(2*EL^2*F10n0*sw^2 - cw^4*vev^2 + cw^2*(2*EL^2*F10n0 + sw^2*vev^2)))/(cw^3*sw*vev^2), 0}, {((2*I)*EL*(cw^2*(F3n0 + FF1n0) + (-F3n0 + FF1n0)*sw^2))/(cw*sw*vev^2), 0}, {((-2*I)*EL*(cw^2*(F3n0 + FF1n0) + (-F3n0 + FF1n0)*sw^2))/(cw*sw*vev^2), 0}},

C[ S[1] , S[1] , V[1] , V[2] ] == {{((-I)*EL^2*FF3n1*(cw^2 + sw^2))/(cw*sw*vev^2), 0}, {((-I)*EL^2*FF3n1*(cw^2 + sw^2))/(cw*sw*vev^2), 0}, {0, 0}, {0, 0}, {((2*I)*EL^2*(cw^2*(F1n2 + 2*(F2n2 + FF2n2)) - (4*F11n2 + F1n2 + 2*F2n2 - 2*FF2n2)*sw^2))/(cw*sw*vev^2), 0}, {0, 0}, {(I*EL^2*FF3n1*(cw^2 + sw^2))/(cw*sw*vev^2), 0}, {0, 0}, {(I*EL^2*FF3n1*(cw^2 + sw^2))/(cw*sw*vev^2), 0}, {0, 0}, {((-2*I)*EL^2*(cw^2*(F1n2 + 2*(F2n2 + FF2n2)) - (4*F11n2 + F1n2 + 2*F2n2 - 2*FF2n2)*sw^2))/(cw*sw*vev^2), 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[1] , V[1] , V[2] ] == {{(I*EL^2*(cw^2*(F1n1 + 2*(F2n1 + FF2n1)) - (4*F11n1 + F1n1 + 2*F2n1 - 2*FF2n1)*sw^2))/(cw*sw*vev), 0}, {((-I)*EL^2*(cw^2*(F1n1 + 2*(F2n1 + FF2n1)) - (4*F11n1 + F1n1 + 2*F2n1 - 2*FF2n1)*sw^2))/(cw*sw*vev), 0}, {((-I)*EL^2*FF3n0*(cw^2 + sw^2))/(cw*sw*vev), 0}, {0, 0}, {(I*EL^2*FF3n0*(cw^2 + sw^2))/(cw*sw*vev), 0}, {0, 0}, {0, 0}},

C[ S[1] , -S[3] , V[3] , V[2] ] == {{(EL^2*(F9n0 + FF3n0))/(cw*vev^2), 0}, {(EL^2*(F3n1 + FF1n1)*(cw^2 + sw^2))/(cw*sw^2*vev^2), 0}, {(EL^2*(F9n0 - FF3n0))/(cw*vev^2), 0}, {-((EL^2*(cw^2*(F3n1 + FF1n1) + (-F3n1 + FF1n1)*sw^2))/(cw*sw^2*vev^2)), 0}, {(2*EL^2*F1n1)/(cw*vev^2), 0}, {-((EL^2*(EL^2*F10n1*sw^2 + cw^2*(EL^2*F10n1 + a*sw^2*vev^2)))/(cw^3*sw^2*vev^2)), 0}, {-((EL^2*(F9n0 + FF3n0))/(cw*vev^2)), 0}, {-((EL^2*(F9n0 - FF3n0))/(cw*vev^2)), 0}, {-((EL^2*(F3n1 + FF1n1)*(cw^2 + sw^2))/(cw*sw^2*vev^2)), 0}, {(EL^2*(cw^2*(F3n1 + FF1n1) + (-F3n1 + FF1n1)*sw^2))/(cw*sw^2*vev^2), 0}, {(-2*EL^2*F1n1)/(cw*vev^2), 0}, {-((cw*EL^2*(F9n0 + FF3n0))/(sw^2*vev^2)), 0}, {(cw*EL^2*(F9n0 + FF3n0))/(sw^2*vev^2), 0}, {0, 0}},

C[ S[2] , -S[3] , V[3] , V[2] ] == {{(I*EL^2*(F3n0 + FF1n0)*(cw - sw)*(cw + sw))/(cw*sw^2*vev^2), 0}, {((-I)*EL^2*(F3n0 + FF1n0)*(cw^2 + sw^2))/(cw*sw^2*vev^2), 0}, {((-I)*EL^2*(cw^2*(F3n0 + FF1n0) + (F3n0 - FF1n0)*sw^2))/(cw*sw^2*vev^2), 0}, {(I*EL^2*(cw^2*(F3n0 + FF1n0) + (-F3n0 + FF1n0)*sw^2))/(cw*sw^2*vev^2), 0}, {((-2*I)*EL^2*F1n0)/(cw*vev^2), 0}, {((I/2)*EL^2*(2*EL^2*F10n0*sw^2 + cw^2*(2*EL^2*F10n0 + sw^2*vev^2)))/(cw^3*sw^2*vev^2), 0}, {((-I)*EL^2*(F3n0 + FF1n0)*(cw - sw)*(cw + sw))/(cw*sw^2*vev^2), 0}, {(I*EL^2*(cw^2*(F3n0 + FF1n0) + (F3n0 - FF1n0)*sw^2))/(cw*sw^2*vev^2), 0}, {(I*EL^2*(F3n0 + FF1n0)*(cw^2 + sw^2))/(cw*sw^2*vev^2), 0}, {((-I)*EL^2*(cw^2*(F3n0 + FF1n0) + (-F3n0 + FF1n0)*sw^2))/(cw*sw^2*vev^2), 0}, {((2*I)*EL^2*F1n0)/(cw*vev^2), 0}, {((2*I)*EL^2*(cw^2*(F3n0 - 4*F5n0 + FF1n0) - 4*F5n0*sw^2))/(cw*sw^2*vev^2), 0}, {((-2*I)*EL^2*(cw^2*(F3n0 + 2*F4n0 + FF1n0) + 2*F4n0*sw^2))/(cw*sw^2*vev^2), 0}, {((-4*I)*EL^2*F4n0*(cw^2 + sw^2))/(cw*sw^2*vev^2), 0}},

C[ -S[3] , V[3] , V[2] ] == {{(2*EL^2*F1n0)/(cw*vev), 0}, {(-2*EL^2*F1n0)/(cw*vev), 0}, {(EL^2*(F3n0 + FF1n0)*(cw^2 + sw^2))/(cw*sw^2*vev), 0}, {-1/2*(EL^2*(2*EL^2*F10n0*sw^2 + cw^2*(2*EL^2*F10n0 + sw^2*vev^2)))/(cw^3*sw^2*vev), 0}, {-((EL^2*(F3n0 + FF1n0)*(cw^2 + sw^2))/(cw*sw^2*vev)), 0}, {-((EL^2*(cw^2*(F3n0 + FF1n0) + (-F3n0 + FF1n0)*sw^2))/(cw*sw^2*vev)), 0}, {(EL^2*(cw^2*(F3n0 + FF1n0) + (-F3n0 + FF1n0)*sw^2))/(cw*sw^2*vev), 0}},

C[ S[1] , S[3] , -V[3] , V[2] ] == {{-((EL^2*(F9n0 + FF3n0))/(cw*vev^2)), 0}, {-((EL^2*(F3n1 + FF1n1)*(cw^2 + sw^2))/(cw*sw^2*vev^2)), 0}, {-((EL^2*(F9n0 - FF3n0))/(cw*vev^2)), 0}, {(EL^2*(cw^2*(F3n1 + FF1n1) + (-F3n1 + FF1n1)*sw^2))/(cw*sw^2*vev^2), 0}, {(-2*EL^2*F1n1)/(cw*vev^2), 0}, {(EL^2*(a*cw^2 + (EL^2*F10n1*(cw^2 + sw^2))/(sw^2*vev^2)))/cw^3, 0}, {(EL^2*(F9n0 + FF3n0))/(cw*vev^2), 0}, {(EL^2*(F9n0 - FF3n0))/(cw*vev^2), 0}, {(EL^2*(F3n1 + FF1n1)*(cw^2 + sw^2))/(cw*sw^2*vev^2), 0}, {-((EL^2*(cw^2*(F3n1 + FF1n1) + (-F3n1 + FF1n1)*sw^2))/(cw*sw^2*vev^2)), 0}, {(2*EL^2*F1n1)/(cw*vev^2), 0}, {(cw*EL^2*(F9n0 + FF3n0))/(sw^2*vev^2), 0}, {-((cw*EL^2*(F9n0 + FF3n0))/(sw^2*vev^2)), 0}, {0, 0}},

C[ S[2] , S[3] , -V[3] , V[2] ] == {{(I*EL^2*(F3n0 + FF1n0)*(cw - sw)*(cw + sw))/(cw*sw^2*vev^2), 0}, {((-I)*EL^2*(F3n0 + FF1n0)*(cw^2 + sw^2))/(cw*sw^2*vev^2), 0}, {((-I)*EL^2*(cw^2*(F3n0 + FF1n0) + (F3n0 - FF1n0)*sw^2))/(cw*sw^2*vev^2), 0}, {(I*EL^2*(cw^2*(F3n0 + FF1n0) + (-F3n0 + FF1n0)*sw^2))/(cw*sw^2*vev^2), 0}, {((-2*I)*EL^2*F1n0)/(cw*vev^2), 0}, {((I/2)*EL^2*(2*EL^2*F10n0*sw^2 + cw^2*(2*EL^2*F10n0 + sw^2*vev^2)))/(cw^3*sw^2*vev^2), 0}, {((-I)*EL^2*(F3n0 + FF1n0)*(cw - sw)*(cw + sw))/(cw*sw^2*vev^2), 0}, {(I*EL^2*(cw^2*(F3n0 + FF1n0) + (F3n0 - FF1n0)*sw^2))/(cw*sw^2*vev^2), 0}, {(I*EL^2*(F3n0 + FF1n0)*(cw^2 + sw^2))/(cw*sw^2*vev^2), 0}, {((-I)*EL^2*(cw^2*(F3n0 + FF1n0) + (-F3n0 + FF1n0)*sw^2))/(cw*sw^2*vev^2), 0}, {((2*I)*EL^2*F1n0)/(cw*vev^2), 0}, {((2*I)*EL^2*(cw^2*(F3n0 - 4*F5n0 + FF1n0) - 4*F5n0*sw^2))/(cw*sw^2*vev^2), 0}, {((-2*I)*EL^2*(cw^2*(F3n0 + 2*F4n0 + FF1n0) + 2*F4n0*sw^2))/(cw*sw^2*vev^2), 0}, {((-4*I)*EL^2*F4n0*(cw^2 + sw^2))/(cw*sw^2*vev^2), 0}},

C[ S[3] , -V[3] , V[2] ] == {{(-2*EL^2*F1n0)/(cw*vev), 0}, {(2*EL^2*F1n0)/(cw*vev), 0}, {-((EL^2*(F3n0 + FF1n0)*(cw^2 + sw^2))/(cw*sw^2*vev)), 0}, {(EL^4*F10n0*(cw^2 + sw^2))/(cw^3*sw^2*vev) + (EL^2*vev)/(2*cw), 0}, {(EL^2*(F3n0 + FF1n0)*(cw^2 + sw^2))/(cw*sw^2*vev), 0}, {(EL^2*(cw^2*(F3n0 + FF1n0) + (-F3n0 + FF1n0)*sw^2))/(cw*sw^2*vev), 0}, {-((EL^2*(cw^2*(F3n0 + FF1n0) + (-F3n0 + FF1n0)*sw^2))/(cw*sw^2*vev)), 0}},

C[ S[1] , S[1] , V[2] , V[2] ] == {{((-1/2*I)*EL^2*(cw^2 + sw^2)*(cw^2*(F9n1 + FF3n1) + (F9n1 - FF3n1)*sw^2))/(cw^2*sw^2*vev^2), 0}, {((-1/2*I)*EL^2*(cw^2 + sw^2)*(cw^2*(F9n1 + FF3n1) + (F9n1 - FF3n1)*sw^2))/(cw^2*sw^2*vev^2), 0}, {((-1/2*I)*EL^2*(cw^2 + sw^2)*(cw^2*(F9n1 + FF3n1) + (F9n1 - FF3n1)*sw^2))/(cw^2*sw^2*vev^2), 0}, {((-1/2*I)*EL^2*(cw^2 + sw^2)*(cw^2*(F9n1 + FF3n1) + (F9n1 - FF3n1)*sw^2))/(cw^2*sw^2*vev^2), 0}, {((4*I)*EL^2*(cw^4*(F2n2 + FF2n2) - cw^2*F1n2*sw^2 + (2*F11n2 + F2n2 - FF2n2)*sw^4))/(cw^2*sw^2*vev^2), 0}, {((I/2)*EL^2*(cw^2 + sw^2)^2*(2*EL^2*F10n2 + b*cw^2*vev^2))/(cw^4*sw^2*vev^2), 0}, {((I/2)*EL^2*(cw^2 + sw^2)*(cw^2*(F9n1 + FF3n1) + (F9n1 - FF3n1)*sw^2))/(cw^2*sw^2*vev^2), 0}, {((I/2)*EL^2*(cw^2 + sw^2)*(cw^2*(F9n1 + FF3n1) + (F9n1 - FF3n1)*sw^2))/(cw^2*sw^2*vev^2), 0}, {((I/2)*EL^2*(cw^2 + sw^2)*(cw^2*(F9n1 + FF3n1) + (F9n1 - FF3n1)*sw^2))/(cw^2*sw^2*vev^2), 0}, {((I/2)*EL^2*(cw^2 + sw^2)*(cw^2*(F9n1 + FF3n1) + (F9n1 - FF3n1)*sw^2))/(cw^2*sw^2*vev^2), 0}, {((-4*I)*EL^2*(cw^4*(F2n2 + FF2n2) - cw^2*F1n2*sw^2 + (2*F11n2 + F2n2 - FF2n2)*sw^4))/(cw^2*sw^2*vev^2), 0}, {((-I)*EL^2*F7n0*(cw^2 + sw^2)^2)/(cw^2*sw^2*vev^2), 0}, {((-I)*EL^2*F7n0*(cw^2 + sw^2)^2)/(cw^2*sw^2*vev^2), 0}, {((-2*I)*EL^2*F6n0*(cw^2 + sw^2)^2)/(cw^2*sw^2*vev^2), 0}},

C[ S[3] , -S[3] , V[2] , V[2] ] == {{((4*I)*EL^2*F3n0)/vev^2, 0}, {((4*I)*EL^2*F3n0)/vev^2, 0}, {((4*I)*EL^2*F3n0)/vev^2, 0}, {((4*I)*EL^2*F3n0)/vev^2, 0}, {((8*I)*EL^2*F1n0)/vev^2, 0}, {(-4*I)*EL^2*(1/2 + (EL^2*F10n0)/(cw^2*vev^2) + (EL^2*F10n0)/(sw^2*vev^2)), 0}, {((-4*I)*EL^2*F3n0)/vev^2, 0}, {((-4*I)*EL^2*F3n0)/vev^2, 0}, {((-4*I)*EL^2*F3n0)/vev^2, 0}, {((-4*I)*EL^2*F3n0)/vev^2, 0}, {((-8*I)*EL^2*F1n0)/vev^2, 0}, {((-4*I)*EL^2*F4n0*(cw^2 + sw^2)^2)/(cw^2*sw^2*vev^2), 0}, {((-4*I)*EL^2*F4n0*(cw^2 + sw^2)^2)/(cw^2*sw^2*vev^2), 0}, {((-8*I)*EL^2*F5n0*(cw^2 + sw^2)^2)/(cw^2*sw^2*vev^2), 0}},

C[ S[1] , V[2] , V[2] ] == {{((2*I)*EL^2*(cw^4*(F2n1 + FF2n1) - cw^2*F1n1*sw^2 + (2*F11n1 + F2n1 - FF2n1)*sw^4))/(cw^2*sw^2*vev), 0}, {((-2*I)*EL^2*(cw^4*(F2n1 + FF2n1) - cw^2*F1n1*sw^2 + (2*F11n1 + F2n1 - FF2n1)*sw^4))/(cw^2*sw^2*vev), 0}, {((-1/2*I)*EL^2*(cw^2 + sw^2)*(cw^2*(F9n0 + FF3n0) + (F9n0 - FF3n0)*sw^2))/(cw^2*sw^2*vev), 0}, {((I/2)*EL^2*(cw^2 + sw^2)^2*(EL^2*F10n1 + a*cw^2*vev^2))/(cw^4*sw^2*vev), 0}, {((I/2)*EL^2*(cw^2 + sw^2)*(cw^2*(F9n0 + FF3n0) + (F9n0 - FF3n0)*sw^2))/(cw^2*sw^2*vev), 0}, {((-1/2*I)*EL^2*(cw^2 + sw^2)*(cw^2*(F9n0 + FF3n0) + (F9n0 - FF3n0)*sw^2))/(cw^2*sw^2*vev), 0}, {((I/2)*EL^2*(cw^2 + sw^2)*(cw^2*(F9n0 + FF3n0) + (F9n0 - FF3n0)*sw^2))/(cw^2*sw^2*vev), 0}},

C[ -S[3] , V[1] , V[1] , V[3] ] == {{(2*EL^3*(F1n0 - F3n0))/(sw*vev), 0}, {(2*EL^3*(F1n0 - F3n0))/(sw*vev), 0}, {(-2*EL^3*(F1n0 - F3n0))/(sw*vev), 0}, {(-2*EL^3*(F1n0 - F3n0))/(sw*vev), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ V[1] , V[3] , -V[3] ] == {{I*EL*(1 - (EL^2*(F1n0 + 2*F2n0 - F3n0 + 2*FF2n0))/sw^2), 0}, {(-I)*EL + ((2*I)*EL^3*(F2n0 + FF2n0))/sw^2, 0}, {(-I)*EL + (I*EL^3*(F1n0 + 2*F2n0 - F3n0 + 2*FF2n0))/sw^2, 0}, {I*EL*(1 - (2*EL^2*(F2n0 + FF2n0))/sw^2), 0}, {I*EL*(1 - (2*EL^2*(F2n0 + FF2n0))/sw^2), 0}, {(-I)*EL + ((2*I)*EL^3*(F2n0 + FF2n0))/sw^2, 0}},

C[ S[1] , V[1] , V[3] , -V[3] ] == {{((-I)*EL^3*(F1n1 + 2*F2n1 - F3n1 + 2*FF2n1))/(sw^2*vev), 0}, {((2*I)*EL^3*(F2n1 + FF2n1))/(sw^2*vev), 0}, {(I*EL^3*(F1n1 + 2*F2n1 - F3n1 + 2*FF2n1))/(sw^2*vev), 0}, {((-2*I)*EL^3*(F2n1 + FF2n1))/(sw^2*vev), 0}, {((-1/2*I)*EL^3*(F9n0 + FF3n0))/(sw^2*vev), 0}, {((I/2)*EL^3*(F9n0 + FF3n0))/(sw^2*vev), 0}, {((-2*I)*EL^3*(F2n1 + FF2n1))/(sw^2*vev), 0}, {((2*I)*EL^3*(F2n1 + FF2n1))/(sw^2*vev), 0}, {0, 0}},

C[ S[1] , S[2] , V[3] , -V[3] ] == {{0, 0}, {-((EL^2*(F3n1 + FF1n1))/(sw^2*vev^2)), 0}, {0, 0}, {(EL^2*(F3n1 + FF1n1))/(sw^2*vev^2), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {(EL^2*(F3n1 + FF1n1))/(sw^2*vev^2), 0}, {-((EL^2*(F3n1 + FF1n1))/(sw^2*vev^2)), 0}, {0, 0}, {(EL^2*(F9n0 + FF3n0))/(sw^2*vev^2), 0}, {-((EL^2*(F9n0 + FF3n0))/(sw^2*vev^2)), 0}, {0, 0}},

C[ S[2] , V[3] , -V[3] ] == {{0, 0}, {0, 0}, {-((EL^2*(F3n0 + FF1n0))/(sw^2*vev)), 0}, {0, 0}, {(EL^2*(F3n0 + FF1n0))/(sw^2*vev), 0}, {(EL^2*(F3n0 + FF1n0))/(sw^2*vev), 0}, {-((EL^2*(F3n0 + FF1n0))/(sw^2*vev)), 0}},

C[ S[3] , -S[3] , V[3] , -V[3] ] == {{(I*EL^2*(F3n0 + FF1n0))/(sw^2*vev^2), 0}, {((-I)*EL^2*(F3n0 + FF1n0))/(sw^2*vev^2), 0}, {((-I)*EL^2*(F3n0 + FF1n0))/(sw^2*vev^2), 0}, {(I*EL^2*(F3n0 + FF1n0))/(sw^2*vev^2), 0}, {0, 0}, {((2*I)*EL^4*F10n0)/(cw^2*sw^2*vev^2), 0}, {((-I)*EL^2*(F3n0 + FF1n0))/(sw^2*vev^2), 0}, {(I*EL^2*(F3n0 + FF1n0))/(sw^2*vev^2), 0}, {(I*EL^2*(F3n0 + FF1n0))/(sw^2*vev^2), 0}, {((-I)*EL^2*(F3n0 + FF1n0))/(sw^2*vev^2), 0}, {0, 0}, {((2*I)*EL^2*(F3n0 - 2*F4n0 - 4*F5n0 + FF1n0))/(sw^2*vev^2), 0}, {((-2*I)*EL^2*(F3n0 + 4*F4n0 + FF1n0))/(sw^2*vev^2), 0}, {((-4*I)*EL^2*(F4n0 + 2*F5n0))/(sw^2*vev^2), 0}},

C[ -S[3] , V[1] , V[3] , V[2] ] == {{-((EL^3*(cw^2*(2*F1n0 - F3n0 + FF1n0) + (F3n0 + FF1n0)*sw^2))/(cw*sw^2*vev)), 0}, {(EL^3*(F3n0 + FF1n0)*(cw^2 + sw^2))/(cw*sw^2*vev), 0}, {(EL^3*(cw^2*(2*F1n0 - F3n0 + FF1n0) + (F3n0 + FF1n0)*sw^2))/(cw*sw^2*vev), 0}, {-((EL^3*(F3n0 + FF1n0)*(cw^2 + sw^2))/(cw*sw^2*vev)), 0}, {0, 0}, {-((EL^3*(F3n0 + FF1n0)*(cw^2 + sw^2))/(cw*sw^2*vev)), 0}, {-((EL^3*(cw^2*(F3n0 + FF1n0) + (2*F1n0 - F3n0 + FF1n0)*sw^2))/(cw*sw^2*vev)), 0}, {(EL^3*(cw^2*(F3n0 + FF1n0) + (2*F1n0 - F3n0 + FF1n0)*sw^2))/(cw*sw^2*vev), 0}, {(EL^3*(F3n0 + FF1n0)*(cw^2 + sw^2))/(cw*sw^2*vev), 0}},

C[ -S[3] , -S[3] , V[3] , V[3] ] == {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {((-4*I)*EL^4*F10n0)/(cw^2*sw^2*vev^2), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {((-4*I)*EL^2*(F4n0 + 2*F5n0))/(sw^2*vev^2), 0}, {((-4*I)*EL^2*(F4n0 + 2*F5n0))/(sw^2*vev^2), 0}, {((-8*I)*EL^2*F4n0)/(sw^2*vev^2), 0}},

C[ S[3] , V[1] , V[1] , -V[3] ] == {{(2*EL^3*(F1n0 - F3n0))/(sw*vev), 0}, {(2*EL^3*(F1n0 - F3n0))/(sw*vev), 0}, {(-2*EL^3*(F1n0 - F3n0))/(sw*vev), 0}, {(-2*EL^3*(F1n0 - F3n0))/(sw*vev), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[3] , V[1] , -V[3] , V[2] ] == {{-((EL^3*(cw^2*(2*F1n0 - F3n0 + FF1n0) + (F3n0 + FF1n0)*sw^2))/(cw*sw^2*vev)), 0}, {(EL^3*(F3n0 + FF1n0)*(cw^2 + sw^2))/(cw*sw^2*vev), 0}, {(EL^3*(cw^2*(2*F1n0 - F3n0 + FF1n0) + (F3n0 + FF1n0)*sw^2))/(cw*sw^2*vev), 0}, {-((EL^3*(F3n0 + FF1n0)*(cw^2 + sw^2))/(cw*sw^2*vev)), 0}, {0, 0}, {-((EL^3*(F3n0 + FF1n0)*(cw^2 + sw^2))/(cw*sw^2*vev)), 0}, {-((EL^3*(cw^2*(F3n0 + FF1n0) + (2*F1n0 - F3n0 + FF1n0)*sw^2))/(cw*sw^2*vev)), 0}, {(EL^3*(cw^2*(F3n0 + FF1n0) + (2*F1n0 - F3n0 + FF1n0)*sw^2))/(cw*sw^2*vev), 0}, {(EL^3*(F3n0 + FF1n0)*(cw^2 + sw^2))/(cw*sw^2*vev), 0}},

C[ V[1] , V[1] , V[3] , -V[3] ] == {{I*EL^2*(1 - (2*EL^2*(F2n0 + FF2n0))/sw^2), 0}, {I*EL^2*(1 - (2*EL^2*(F2n0 + FF2n0))/sw^2), 0}, {(-2*I)*EL^2 + ((4*I)*EL^4*(F2n0 + FF2n0))/sw^2, 0}},

C[ S[2] , V[1] , V[3] , -V[3] ] == {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {(EL^3*(F3n0 + FF1n0))/(sw^2*vev), 0}, {(EL^3*(F3n0 + FF1n0))/(sw^2*vev), 0}, {0, 0}, {0, 0}, {(-2*EL^3*(F3n0 + FF1n0))/(sw^2*vev), 0}},

C[ S[2] , S[2] , V[3] , -V[3] ] == {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {((-4*I)*EL^2*F4n0)/(sw^2*vev^2), 0}, {((-4*I)*EL^2*F4n0)/(sw^2*vev^2), 0}, {((-8*I)*EL^2*F5n0)/(sw^2*vev^2), 0}},

C[ V[3] , -V[3] , V[2] ] == {{((I/2)*EL*(EL^2*(F3n0 + FF1n0)*sw^2 + cw^2*(EL^2*(-4*F2n0 + F3n0 + FF1n0 - 4*FF2n0) + 2*sw^2)))/(cw*sw^3), 0}, {((-1/2*I)*EL*(EL^2*(F3n0 + FF1n0)*sw^2 + cw^2*(EL^2*(-4*F2n0 + F3n0 + FF1n0 - 4*FF2n0) + 2*sw^2)))/(cw*sw^3), 0}, {((-1/2*I)*EL*(EL^2*(F3n0 + FF1n0)*sw^2 + cw^2*(EL^2*(-4*F2n0 + F3n0 + FF1n0 - 4*FF2n0) + 2*sw^2)))/(cw*sw^3), 0}, {((I/2)*EL*(EL^2*(2*F1n0 - F3n0 + FF1n0)*sw^2 + cw^2*(EL^2*(-4*F2n0 + F3n0 + FF1n0 - 4*FF2n0) + 2*sw^2)))/(cw*sw^3), 0}, {((I/2)*EL*(EL^2*(F3n0 + FF1n0)*sw^2 + cw^2*(EL^2*(-4*F2n0 + F3n0 + FF1n0 - 4*FF2n0) + 2*sw^2)))/(cw*sw^3), 0}, {((-1/2*I)*EL*(EL^2*(2*F1n0 - F3n0 + FF1n0)*sw^2 + cw^2*(EL^2*(-4*F2n0 + F3n0 + FF1n0 - 4*FF2n0) + 2*sw^2)))/(cw*sw^3), 0}},

C[ S[1] , V[3] , -V[3] , V[2] ] == {{((-1/2*I)*EL^3*(cw^2*(4*F2n1 - F3n1 - FF1n1 + 4*FF2n1) - (F3n1 + FF1n1)*sw^2))/(cw*sw^3*vev), 0}, {((I/2)*EL^3*(cw^2*(4*F2n1 - F3n1 - FF1n1 + 4*FF2n1) - (F3n1 + FF1n1)*sw^2))/(cw*sw^3*vev), 0}, {((I/2)*EL^3*(cw^2*(4*F2n1 - F3n1 - FF1n1 + 4*FF2n1) - (F3n1 + FF1n1)*sw^2))/(cw*sw^3*vev), 0}, {((-1/2*I)*EL^3*(cw^2*(4*F2n1 - F3n1 - FF1n1 + 4*FF2n1) - (F3n1 + FF1n1)*sw^2))/(cw*sw^3*vev), 0}, {0, 0}, {((I/2)*EL^3*(F9n0 + FF3n0))/(cw*sw*vev), 0}, {((-1/2*I)*EL^3*(cw^2*(4*F2n1 - F3n1 - FF1n1 + 4*FF2n1) + (-2*F1n1 + F3n1 - FF1n1)*sw^2))/(cw*sw^3*vev), 0}, {((I/2)*EL^3*(cw^2*(4*F2n1 - F3n1 - FF1n1 + 4*FF2n1) + (-2*F1n1 + F3n1 - FF1n1)*sw^2))/(cw*sw^3*vev), 0}, {((-1/2*I)*EL^3*(F9n0 + FF3n0))/(cw*sw*vev), 0}},

C[ -S[3] , V[3] , V[3] , -V[3] ] == {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {(2*EL^3*(F3n0 + 2*F4n0 + FF1n0))/(sw^3*vev), 0}, {-((EL^3*(F3n0 - 2*F4n0 - 4*F5n0 + FF1n0))/(sw^3*vev)), 0}, {0, 0}, {0, 0}, {-((EL^3*(F3n0 - 2*F4n0 - 4*F5n0 + FF1n0))/(sw^3*vev)), 0}},

C[ S[3] , S[3] , -V[3] , -V[3] ] == {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {((-4*I)*EL^4*F10n0)/(cw^2*sw^2*vev^2), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {((-4*I)*EL^2*(F4n0 + 2*F5n0))/(sw^2*vev^2), 0}, {((-4*I)*EL^2*(F4n0 + 2*F5n0))/(sw^2*vev^2), 0}, {((-8*I)*EL^2*F4n0)/(sw^2*vev^2), 0}},

C[ S[3] , V[3] , -V[3] , -V[3] ] == {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {-((EL^3*(F3n0 - 2*F4n0 - 4*F5n0 + FF1n0))/(sw^3*vev)), 0}, {-((EL^3*(F3n0 - 2*F4n0 - 4*F5n0 + FF1n0))/(sw^3*vev)), 0}, {0, 0}, {0, 0}, {(2*EL^3*(F3n0 + 2*F4n0 + FF1n0))/(sw^3*vev), 0}},

C[ V[3] , V[3] , -V[3] , -V[3] ] == {{(I*EL^2*(EL^2*(2*F2n0 - F3n0 + F4n0 + 2*F5n0 - FF1n0 + 2*FF2n0) - sw^2))/sw^4, 0}, {(I*EL^2*(EL^2*(2*F2n0 - F3n0 + F4n0 + 2*F5n0 - FF1n0 + 2*FF2n0) - sw^2))/sw^4, 0}, {((-2*I)*EL^2*(EL^2*(2*F2n0 - F3n0 - F4n0 - FF1n0 + 2*FF2n0) - sw^2))/sw^4, 0}},

C[ S[2] , S[2] , S[2] , V[2] ] == {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {(-16*EL*(F4n0 + F5n0)*(cw^2 + sw^2))/(cw*sw*vev^3), 0}, {(-16*EL*(F4n0 + F5n0)*(cw^2 + sw^2))/(cw*sw*vev^3), 0}, {(-16*EL*(F4n0 + F5n0)*(cw^2 + sw^2))/(cw*sw*vev^3), 0}},

C[ -S[3] , V[3] , V[2] , V[2] ] == {{0, 0}, {(2*EL^3*(F1n0 - F3n0))/(sw*vev), 0}, {0, 0}, {(-2*EL^3*(F1n0 - F3n0))/(sw*vev), 0}, {(EL^3*(cw^2 + sw^2)*(cw^2*(F3n0 + 2*F4n0 + FF1n0) + 2*F4n0*sw^2))/(cw^2*sw^3*vev), 0}, {(EL^3*(cw^2 + sw^2)*(cw^2*(F3n0 + 2*F4n0 + FF1n0) + 2*F4n0*sw^2))/(cw^2*sw^3*vev), 0}, {(2*EL^3*(F1n0 - F3n0))/(sw*vev), 0}, {(-2*EL^3*(F1n0 - F3n0))/(sw*vev), 0}, {(-2*EL^3*(cw^2 + sw^2)*(cw^2*(F3n0 - 2*F5n0 + FF1n0) - 2*F5n0*sw^2))/(cw^2*sw^3*vev), 0}},

C[ V[1] , V[3] , -V[3] , V[2] ] == {{((-I)*EL^2*(EL^2*(F3n0 + FF1n0)*sw^2 + cw^2*(EL^2*(-4*F2n0 + F3n0 + FF1n0 - 4*FF2n0) + 2*sw^2)))/(cw*sw^3), 0}, {((I/2)*EL^2*(EL^2*(F3n0 + FF1n0)*sw^2 + cw^2*(EL^2*(-4*F2n0 + F3n0 + FF1n0 - 4*FF2n0) + 2*sw^2)))/(cw*sw^3), 0}, {((I/2)*EL^2*(EL^2*(F3n0 + FF1n0)*sw^2 + cw^2*(EL^2*(-4*F2n0 + F3n0 + FF1n0 - 4*FF2n0) + 2*sw^2)))/(cw*sw^3), 0}},

C[ S[2] , V[3] , -V[3] , V[2] ] == {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {(-2*EL^3*(cw^2*(F3n0 - 2*F5n0 + FF1n0) - 2*F5n0*sw^2))/(cw*sw^3*vev), 0}, {(EL^3*(cw^2*(F3n0 + 2*F4n0 + FF1n0) + 2*F4n0*sw^2))/(cw*sw^3*vev), 0}, {0, 0}, {0, 0}, {(EL^3*(cw^2*(F3n0 + 2*F4n0 + FF1n0) + 2*F4n0*sw^2))/(cw*sw^3*vev), 0}},

C[ S[3] , -V[3] , V[2] , V[2] ] == {{0, 0}, {(2*EL^3*(F1n0 - F3n0))/(sw*vev), 0}, {0, 0}, {(-2*EL^3*(F1n0 - F3n0))/(sw*vev), 0}, {(EL^3*(cw^2 + sw^2)*(cw^2*(F3n0 + 2*F4n0 + FF1n0) + 2*F4n0*sw^2))/(cw^2*sw^3*vev), 0}, {(EL^3*(cw^2 + sw^2)*(cw^2*(F3n0 + 2*F4n0 + FF1n0) + 2*F4n0*sw^2))/(cw^2*sw^3*vev), 0}, {(2*EL^3*(F1n0 - F3n0))/(sw*vev), 0}, {(-2*EL^3*(F1n0 - F3n0))/(sw*vev), 0}, {(-2*EL^3*(cw^2 + sw^2)*(cw^2*(F3n0 - 2*F5n0 + FF1n0) - 2*F5n0*sw^2))/(cw^2*sw^3*vev), 0}},

C[ S[2] , S[2] , V[2] , V[2] ] == {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {((-8*I)*EL^2*(F4n0 + F5n0)*(cw^2 + sw^2)^2)/(cw^2*sw^2*vev^2), 0}, {((-8*I)*EL^2*(F4n0 + F5n0)*(cw^2 + sw^2)^2)/(cw^2*sw^2*vev^2), 0}, {((-8*I)*EL^2*(F4n0 + F5n0)*(cw^2 + sw^2)^2)/(cw^2*sw^2*vev^2), 0}},

C[ V[3] , -V[3] , V[2] , V[2] ] == {{(I*EL^2*(cw^2*EL^2*(F3n0 + 2*F4n0 + FF1n0)*sw^2 + EL^2*F4n0*sw^4 + cw^4*(EL^2*(-2*F2n0 + F3n0 + F4n0 + FF1n0 - 2*FF2n0) + sw^2)))/(cw^2*sw^4), 0}, {(I*EL^2*(cw^2*EL^2*(F3n0 + 2*F4n0 + FF1n0)*sw^2 + EL^2*F4n0*sw^4 + cw^4*(EL^2*(-2*F2n0 + F3n0 + F4n0 + FF1n0 - 2*FF2n0) + sw^2)))/(cw^2*sw^4), 0}, {(2*I)*EL^2*((EL^2*F5n0)/cw^2 - (EL^2*(F3n0 - 2*F5n0 + FF1n0))/sw^2 - (cw^2*(EL^2*(-2*F2n0 + F3n0 - F5n0 + FF1n0 - 2*FF2n0) + sw^2))/sw^4), 0}},

C[ S[2] , V[2] , V[2] , V[2] ] == {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {(4*EL^3*(F4n0 + F5n0)*(cw^2 + sw^2)^3)/(cw^3*sw^3*vev), 0}, {(4*EL^3*(F4n0 + F5n0)*(cw^2 + sw^2)^3)/(cw^3*sw^3*vev), 0}, {0, 0}, {0, 0}, {(4*EL^3*(F4n0 + F5n0)*(cw^2 + sw^2)^3)/(cw^3*sw^3*vev), 0}},

C[ V[2] , V[2] , V[2] , V[2] ] == {{((2*I)*EL^4*(F4n0 + F5n0)*(cw^2 + sw^2)^4)/(cw^4*sw^4), 0}, {((2*I)*EL^4*(F4n0 + F5n0)*(cw^2 + sw^2)^4)/(cw^4*sw^4), 0}, {((2*I)*EL^4*(F4n0 + F5n0)*(cw^2 + sw^2)^4)/(cw^4*sw^4), 0}}

}

